#!/usr/bin/env python3
"""Validate a generated BYR Markdown summary."""

from __future__ import annotations

import argparse
import json
from pathlib import Path
import re


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--input", type=Path, required=True)
    parser.add_argument(
        "--schema",
        type=Path,
        default=Path(__file__).with_name("summary-schema.json"),
    )
    parser.add_argument("--report", type=Path, default=Path("validation.json"))
    args = parser.parse_args()

    markdown = args.input.read_text(encoding="utf-8")
    schema = json.loads(args.schema.read_text(encoding="utf-8"))
    errors: list[str] = []
    if not re.search(schema["title_regex"], markdown, flags=re.MULTILINE):
        errors.append("标题格式不符合要求")
    for section in schema["required_sections"]:
        if section not in markdown:
            errors.append(f"缺少章节：{section}")
    if "https://bbs.byr.cn/" not in markdown:
        errors.append("没有找到北邮人论坛原帖链接")

    result = {"valid": not errors, "errors": errors}
    args.report.write_text(json.dumps(result, ensure_ascii=False, indent=2) + "\n", encoding="utf-8")
    print("VALID" if result["valid"] else "INVALID")
    return 0 if result["valid"] else 2


if __name__ == "__main__":
    raise SystemExit(main())
